### ISSUE TITLE
Warning: Replace createClass

### ISSUE THREAD

**Issue by jricaldi** [nygardk/react-break#8]
I get this warning.

`
Warning: A Component: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.`

Very scary xD

**Comment by renet** [comment]
Thanks for posting this. Wanted to post this for a while, but didn't find the time. +1 from me!

**Comment by nygardk** [comment]
This should had been fixed in `v1.2.0` (see release notes).

Are you sure you are not using an older version?

**Comment by renet** [comment]
Well, I'm using exactly `v1.2.0` and the error still occurs. createClass is used in line 87 of react-break.jsx, inside the `createComponent` method of the layoutGenerator:

```javascript
const layoutGenerator = function componentGenerator(breakpoints) {
  function createComponent(method, breakpoint) {
    if (!Object.keys(breakpoints).includes(breakpoint)) {
      throw new Error(`Invalid breakpoint name '${breakpoint}'` +
        '(not defined in layout).');
    }

    return React.createClass({
      propTypes: {
        children: PropTypes.oneOfType([
          PropTypes.arrayOf(PropTypes.node),
          PropTypes.node,
        ]),
      },

      render() {
        const {
          children,
        } = this.props;

        return children ? (
          <Break
            {...this.props}
            breakpoints={breakpoints}
            query={{ method, breakpoint }}>
            {children}
          </Break>
        ) : null;
      },
    });
  }

  return {
    is: breakpoint => createComponent('is', breakpoint),
    isAtLeast: breakpoint => createComponent('isAtLeast', breakpoint),
    isAtMost: breakpoint => createComponent('isAtMost', breakpoint),
  };
};
```

**Comment by nygardk** [comment]
Oh, I missed that. Will fix.

**Comment by nygardk** [comment]
Fixed in `v1.2.1`
